### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tkrestiankova** [rafaski1/currency_converter_api#1]
- [x] Incorrect redis key value in [forex_lient.py#L31]( https://github.com/rafaski1/currency_converter_api/blob/main/currency_converter_api/forex_client.py#L31)
- [x] Validate input for all ForexClient methods
- [x] Create an Enum class for Forex endpoints

Example:
```
...
class ForexEndpoint(str, Enum):
    FETCH_ONE = "fetch-one"
...

async def get_currency_rate(self, from_curr: str, to_curr: str) -> float:
    self.redis_key = f"{from_curr}-{to_curr}"
    endpoint = ForexEndpoint.FETCH_ONE
```

- [x] Return an API key in the `/create_user` endpoint
- [x] Verify all endpoints (`api-key` header) except for the `/create_user`
- [x] Create an endpoint `/list_users` that will list all signed up users 

Output example:
```
{
    "success": True,
    "message": None,
    "results": [
        "johndoe1@gmail.com",
        "johndoe2@gmail.com",
        "johndoe3@gmail.com",
        ...
    ]
}
```

**Comment by tkrestiankova** [comment]
> Return an API key in the /create_user endpoint

Create a unique api key for each user (you will have to store that information in redis)

> Verify all endpoints (api-key header) except for the /create_user

Try using routers - create 1 router for endpoints that need the verification and another router for those that do not need verification

cc @rafaski1
