### ISSUE TITLE
TODO pt.2

### ISSUE THREAD

**Issue by tkrestiankova** [rafaski1/currency_converter_api#4]
- [x] Create a database with registered users
    - Work with sqlalchemy
    - The table should have (at least) these columns: email, password, concurrency, credits, subscription, expiration
- [x] Store user into database once created, set defaults
- [ ] Verify requests using the database (not redis cache)
- [ ] Create subscriptions instead of creating users (pass email and subscription type)
- [ ] Credits deduction (deduct X credits for each request)

TO WRAP UP
- [ ] Docstrings
- [ ] Dockerfile
- [ ] README.md (project description + how to run the app)
- [ ] Code review
